import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Navigation } from "../../../components/navigation";

type Props = {
  userName: string;
};
const Home: NextPage<Props> = ({ userName }) => {
  return (
    <>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>User: {userName}</h1>

        <Navigation />
      </main>
    </>
  );
};
export default Home;

type Query = {
  userName: string;
};
export const getStaticProps: GetStaticProps<Props, Query> = async ({
  params,
}) => {
  const userName = params.userName;

  return {
    props: { userName },
    revalidate: 60,
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};
