import Head from "next/head";
import { FC } from "react";
import { Navigation } from "../../components/navigation";

type Props = {
  userName: string;
};
const Home: FC<Props> = ({ userName }) => {
  return (
    <>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>User: {userName}</h1>

        <Navigation />
      </main>
    </>
  );
};
export default Home;

export const getStaticProps = ({ params }) => {
  const userName = params.userName;

  return {
    props: { userName },
    revalidate: 60,
  };
};

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: true,
  };
};
